export const CONTACT_FORM_LABELS = {
  enquiryTitle: 'Send a message',
  enquiryLead: 'Ask about dining, events, or anything else. Switch to booking when you want a room.',
  bookTitle: 'Book a stay',
  bookLead: "Choose a room first. The calendar then shows that room's available dates.",
  intentEnquiry: 'General enquiry',
  intentBook: 'Book a room',
  firstName: 'First name',
  lastName: 'Last name',
  email: 'Email',
  mobile: 'Mobile (WhatsApp)',
  checkIn: 'Check-in',
  checkOut: 'Check-out',
  adults: 'Adults',
  children: 'Children',
  roomType: 'Room',
  roomTypeDefault: 'Choose a room',
  message: 'Your message',
  messagePlaceholder: 'Tell us what you need, or any notes for your stay…',
  requests: 'Special requests',
  requestsPlaceholder: 'Anything we should know ahead of your stay?',
  submit: 'Send enquiry',
  submitting: 'Sending…',
  continueBook: 'Continue to booking',
  switchBook: 'I want to book a room',
  switchEnquiry: 'Just send a message',
}
