import {
  AlarmClock,
  Bath,
  BedDouble,
  Bell,
  Building2,
  Bug,
  Car,
  Check,
  Coffee,
  Droplets,
  Fan,
  GlassWater,
  LampDesk,
  Lock,
  Luggage,
  Moon,
  Palmtree,
  Phone,
  Plug,
  Refrigerator,
  Satellite,
  Shirt,
  Snowflake,
  Sofa,
  Sparkle,
  Sparkles,
  Thermometer,
  TreePine,
  Trees,
  Tv,
  Wifi,
  Wind,
} from 'lucide-react'

const FEATURE_ICONS = {
  wifi: Wifi,
  ac: Snowflake,
  fan: Fan,
  heating: Thermometer,
  tv: Tv,
  satellite: Satellite,
  blackout: Moon,
  'extra-bedding': BedDouble,
  mosquito: Bug,
  bath: Bath,
  shower: Droplets,
  'hot-water': Droplets,
  hairdryer: Wind,
  toiletries: Sparkles,
  towels: Bath,
  desk: LampDesk,
  wardrobe: Shirt,
  luggage: Luggage,
  safe: Lock,
  sofa: Sofa,
  fridge: Refrigerator,
  kettle: Coffee,
  'tea-coffee': Coffee,
  water: GlassWater,
  iron: Shirt,
  phone: Phone,
  alarm: AlarmClock,
  socket: Plug,
  balcony: TreePine,
  terrace: Palmtree,
  'garden-view': Trees,
  'city-view': Building2,
  housekeeping: Sparkle,
  'room-service': Bell,
  laundry: Shirt,
  parking: Car,
}

export function FeatureIcon({ id, size = 16, className }) {
  const Icon = FEATURE_ICONS[id] || Check
  return <Icon size={size} className={className} />
}
